schema_version: 20180708
name: javafn
version: 0.0.2
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.75
run_image: fnproject/fn-java-fdk:jdk9-1.0.75
cmd: com.example.fn.HelloFunction::handleRequest
format: http-stream
triggers:
- name: javafn-trigger
  type: http
  source: /javafn-trigger
